spring:
  logging:
    level:
      org.hibernate.SQL: debug
  datasource:
    url: jdbc:postgresql://localhost:5432/growsync?options=-c%20TimeZone=UTC
    username: growsync
    password: growsync123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
